
scala_stack:
  compiler:
    libs: /APP/libs/
    src: /APP/src/
  environment: DOCKER
  javascriptUrl: http://localhost:8081/app.js

server:
  address: 0.0.0.0

logging:
  level:
    org: INFO
    com.github.aimmoth: DEBUG
